options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/project-6ce05f8d-7a09-4456-849/report-agent/report-agent:latest', '.']

images:
  - 'southamerica-east1-docker.pkg.dev/project-6ce05f8d-7a09-4456-849/report-agent/report-agent:latest'
